services:
  backend:
    volumes:
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/movies.db
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:9087/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
